---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt::default]
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      cpus: 2
      memory: 512
- name: centos-6.4
  run_list:
  - recipe[yum::epel]
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    customize:
      cpus: 2
      memory: 512

suites:
- name: default
  run_list:
  - recipe[rs-lamp]
  - recipe[rs-mysql::default]
  - recipe[rs-application_php]
  - recipe[rs-lamp::dump_import]
  - recipe[curl]
  attributes:
    cloud:
      provider: 'vagrant'
      public_ips: ['10.10.1.1']
      private_ips: ['10.0.2.15']
    rs-mysql:
      lineage: 'lineage'
      server_root_password: rootpass
      server_repl_password: replpass
      server_usage: dedicated
      application_username: appuser
      application_password: apppass
      application_database_name: app_test
    rs-application_php:
      application_name: example
      local_settings_file: config/db.php
      scm:
        provider: git
        revision: unified_php
        repository: git://github.com/rightscale/examples.git
      database:
        provider: mysql
        host: localhost
        user: appuser
        password: apppass
        schema: app_test
    rs-lamp:
      dump_file: app_test.sql

- name: dump_import_gz
  run_list:
  - recipe[rs-lamp]
  - recipe[rs-mysql::default]
  - recipe[rs-application_php]
  - recipe[rs-lamp::dump_import]
  - recipe[curl]
  attributes:
    cloud:
      provider: 'vagrant'
      public_ips: ['10.10.1.1']
      private_ips: ['10.0.2.15']
    rs-mysql:
      lineage: 'lineage'
      server_root_password: rootpass
      server_repl_password: replpass
      server_usage: dedicated
      application_username: appuser
      application_password: apppass
      application_database_name: app_test
    rs-application_php:
      application_name: example
      local_settings_file: config/db.php
      scm:
        provider: git
        revision: unified_php
        repository: git://github.com/rightscale/examples.git
      database:
        provider: mysql
        host: localhost
        user: appuser
        password: apppass
        schema: app_test
    rs-lamp:
      dump_file: app_test.sql.gz

- name: dump_import_bz2
  run_list:
  - recipe[rs-lamp]
  - recipe[rs-mysql::default]
  - recipe[rs-application_php]
  - recipe[rs-lamp::dump_import]
  - recipe[curl]
  attributes:
    cloud:
      provider: 'vagrant'
      public_ips: ['10.10.1.1']
      private_ips: ['10.0.2.15']
    rs-mysql:
      lineage: 'lineage'
      server_root_password: rootpass
      server_repl_password: replpass
      server_usage: dedicated
      application_username: appuser
      application_password: apppass
      application_database_name: app_test
    rs-application_php:
      application_name: example
      local_settings_file: config/db.php
      scm:
        provider: git
        revision: unified_php
        repository: git://github.com/rightscale/examples.git
      database:
        provider: mysql
        host: localhost
        user: appuser
        password: apppass
        schema: app_test
    rs-lamp:
      dump_file: app_test.sql.bz2

- name: dump_import_xz
  run_list:
  - recipe[rs-lamp]
  - recipe[rs-mysql::default]
  - recipe[rs-application_php]
  - recipe[rs-lamp::dump_import]
  - recipe[curl]
  attributes:
    cloud:
      provider: 'vagrant'
      public_ips: ['10.10.1.1']
      private_ips: ['10.0.2.15']
    rs-mysql:
      lineage: 'lineage'
      server_root_password: rootpass
      server_repl_password: replpass
      server_usage: dedicated
      application_username: appuser
      application_password: apppass
      application_database_name: app_test
    rs-application_php:
      application_name: example
      local_settings_file: config/db.php
      scm:
        provider: git
        revision: unified_php
        repository: git://github.com/rightscale/examples.git
      database:
        provider: mysql
        host: localhost
        user: appuser
        password: apppass
        schema: app_test
    rs-lamp:
      dump_file: app_test.sql.xz
